JENKINS_TESTTYPES:
  - bareos-client-only+bareos-universal-client+bareos-postgresql
  - univention-bareos

OS:
  Fedora:
    "37":
      TYPE: rpm
      IMAGE: fedora37
      ARCH:
      - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - python-bareos
  win:
    cross:
      TYPE: win
      STAGES:
        - win-64-release
      ARCH:
       - x86_64
      WINVERSIONS:
         - windows-10-32
         - windows-10-64
